// Stocka brand assets for reports.
//
// Drawn as inline SVG rather than embedding src/assets/icon.png, for three
// reasons that all matter here:
//
//   1. Size. The PNG is 808KB; base64 would add ~1.1MB to EVERY generated
//      report — the whole PDF is currently 140KB — and that payload would cross
//      IPC on every preview.
//   2. Print quality. A report is printed. Vector stays crisp at any size and
//      on any printer; a raster mark scaled into a page header does not.
//   3. Packaging. electron-builder ships src/assets/icon.png but not
//      full_logo.png, and reading either from disk inside an ASAR at runtime is
//      a path problem waiting to happen. A string has no such failure mode.
//
// The green is sampled from the icon itself (#005818), not guessed.

const BRAND = {
  green: '#005818',
  greenDark: '#00420f',
  greenLight: '#0a7a26',
  name: 'Stocka',
  system: 'Retail Management System',
  url: 'www.stocka.co.zw',
}

/**
 * The Stocka mark: a bold S with flat-cut terminals in a rounded square.
 *
 * The S is a stroked path with butt caps, which is what produces the squared-off
 * terminals of the real mark — a filled glyph would round them.
 */
const S_PATH =
  'M45 25.5 C45 21 39.5 18.5 32 18.5 C24.5 18.5 19 21 19 25.5 ' +
  'C19 30 24.5 31.6 32 32.3 C39.5 33 45 34.6 45 39.2 ' +
  'C45 43.7 39.5 46.2 32 46.2 C24.5 46.2 19 43.7 19 39.2'

function stockaMark(size = 48, { rounded = true } = {}) {
  return (
    `<svg class="brand-mark" width="${size}" height="${size}" viewBox="0 0 64 64" ` +
    `xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Stocka">` +
    `<rect width="64" height="64" rx="${rounded ? 14 : 0}" fill="${BRAND.green}"/>` +
    `<path d="${S_PATH}" fill="none" stroke="#ffffff" stroke-width="9.5" stroke-linecap="butt"/>` +
    `</svg>`
  )
}

/** The mark as a data URI — for Chromium's print footer, which will not take inline SVG. */
function stockaMarkDataUri(size = 16) {
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 64 64">` +
    `<rect width="64" height="64" rx="14" fill="${BRAND.green}"/>` +
    `<path d="${S_PATH}" fill="none" stroke="#ffffff" stroke-width="9.5" stroke-linecap="butt"/>` +
    `</svg>`
  return 'data:image/svg+xml;base64,' + Buffer.from(svg, 'utf8').toString('base64')
}

/**
 * The full lockup — STOCKA over RETAIL MANAGEMENT SYSTEM — as HTML rather than
 * SVG text, so it uses the document's own font stack instead of depending on a
 * typeface being installed on whatever machine renders the PDF.
 */
function stockaLockup({ markSize = 64 } = {}) {
  return (
    `<div class="brand-lockup">` +
    stockaMark(markSize) +
    `<div class="brand-words">` +
    `<div class="brand-name">STOCKA</div>` +
    `<div class="brand-system">RETAIL MANAGEMENT SYSTEM</div>` +
    `</div></div>`
  )
}

/** One line for the bottom of a screen/HTML report. */
function generatedByLine() {
  return (
    `<span class="generated-by">` +
    stockaMark(11) +
    `<span>Generated by ${BRAND.name} ${BRAND.system}</span>` +
    `</span>`
  )
}

module.exports = { BRAND, stockaMark, stockaMarkDataUri, stockaLockup, generatedByLine }
