const w = window.stocka.stock

export const addStockReceiving = (r) => w.addReceiving(r)
export const getStockReceivings = () => w.getAll()
export const getStockReceivingById = (id) => w.getById(id)
export const getAllPurchaseHistory = () => w.getAllPurchases()
export const recordDirectPurchase = (p) => w.recordDirect(p)
export const getDeadStockProducts = (days) => w.getDeadStock(days)
export const getRestockNeeded = () => w.getRestock()
export const getProductSalesVelocity = (days) => w.getVelocity(days)
export const getExpiringProducts = (days) => w.getExpiring(days)
export const getExpiredProducts = () => w.getExpired()
export const getExpiryReport = () => w.getExpiryReport()
export const discardExpiredBatch = (productId, expiryDate, units, by) => w.discardExpiredBatch(productId, expiryDate, units, by)
export const importStockReceivings  = (rows, by)               => w.importReceivings(rows, by)
export const reconcileProduct       = (id, qty, notes, by)     => w.reconcileProduct(id, qty, notes, by)
export const reconcileProducts      = (adjustments, by)        => w.reconcileProducts(adjustments, by)
export const recordInitialCost      = (id, cost, by)           => w.recordInitialCost(id, cost, by)
export const correctStockReceiving  = (id, corrected, by)      => w.correctReceiving(id, corrected, by)
export const recordStockLoss        = (loss)                   => w.recordLoss(loss)
export const reverseStockLoss       = (id, reason, by)         => w.reverseLoss(id, reason, by)
export const getStockLosses         = (filters)                => w.getLosses(filters)
export const getStockLossSummary    = (range)                  => w.getLossSummary(range)
export const getReconciliationSnapshot   = (range)             => w.reconSnapshot(range)
export const reconcileProductExplained   = (id, qty, why, by)  => w.reconcileExplained(id, qty, why, by)
export const reconcileProductsExplained  = (entries, by)       => w.reconcileExplainedMany(entries, by)
